spring:
  application:
    name: haru-court

  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

jwt:
  access-expiration-time: 3600000 # 1시간
  refresh-expiration-time: 2592000000 # 30일
  prefix: Bearer
  secret: ${JWT_SECRET}

oauth:
  google:
    client-id: ${GOOGLE_CLIENT_ID}